@startuml
!include hdr.puml
|HelpDesk User|
start
:**HelpDesk User** принимает звонок
от клиента который сообщает
код заказа и описывает проблему;
if (Клиента можно идентифицировать
в системе по его номеру телефона?) then (да)
        :Клиент подтягивается
        из базы;
    if (Заказ можно идентифицировать
      в системе по коду заказа?) then (да)
            :Заказ подтягивается
            из базы;
        else (нет)
            :Заказ создается с помощью формы
        и привязывается к данному клиенту;
    endif
    else (нет)
        :Клиент и его заказ создаются
        с помощью формы;
endif
:**HelpDesk User** выбирает определенную услугу
и создает обращение на данный заказ;
:На данное обращение создается инцидент
привязанный к определенной услуге
и рабочей группе;
:**SL3 Manager** для данной рабочей группы
уведомляется по email;
|#AntiqueWhite|SL3 Manager|
:**SL3 Manager** назначает данный инцидент
на **SL3 User** из своей группы;
|#AliceBlue|SL3 User|
:**SL3 User** берет инцидент в работу
и привязывает к нему определенный
бизнес-процесс;
:**SL3 User** выполняет работу по инциденту
и закрывает его;
:Отсылается уведомление о закрытии
инцидента для **SL3 Manager**;
:Закрывается соответствующее обращение;
:Отсылаются уведомления о закрытии
обращения для **HelpDesk User**,
**HelpDesk Manager** и клиента;
stop
@enduml