@startuml
!include hdr.puml

title CRM classes diagram

package Models #DDDDDD {
    class Client {
      name : String
      middlename : String
      surname : String
      phonenumber : String
      email : String
      inn : Integer
      firmname : String
    }
    class Order {
      orderdate : Date
      code : String
      narrative : String
      cost : BigDecimal
    }

    class Servicerequest {
      requesttime : Date
      narrative : String
      userid : Integer
    }

    class Incident {
      incidenttime : Date
      businessprocess : String
      userid : Integer
    }

    class Status {
      statustime : Date
      status : String
      narrative : String
    }

    class Service {
      code : String
      description : String
    }

    class Servicegroup {
      code : String
      description : String
      groupemail : String
      managerid : Integer
    }
}

package Repositories #DDDDDD {
    class ClientRepository {
    }
    class OrderRepository {
    }
    class ServiceRequestRepository {
    }
    class IncidentRepository {
    }
}

Client "1  " -- "*" Order
Order "0 " -- "* " Servicerequest
Servicerequest "0" - "1" Incident
Incident "1 " -- "1  " Service
Service "1" - "1" Servicegroup
Incident "1" -- "*" Status
Servicerequest "1" -- "*" Status

package Services #DDDDDD {
    class ServiceRequestManager {
        GetSRListByUser(User u) : List<ServiceRequest>
        SetSRStatus(ServiceRequest sr, Status st)
        CreateSRByClient(Client cl) : ServiceRequest
    }
    class IncidentManager {
          GetIncListByUser(User u) : List<Incident>
          SetIncStatus(Incident inc, Status st)
          CreateIncBySR(ServiceRequest sr) : Incident
    }
    class ClientProxy {
        GetClientList() : List<Client>
        GetClientByPNumber(String pNumber) : Client
        UpdateClientByID(Integer id, Client cl)
        CreateNewClient() : Client
        GetClientByID(Integer id) : Client
    }
    class OrderProxy {
            GetOrderList() : List<Order>
            GetOrderByCode(String code) : Order
            UpdateOrderID(Integer id, Order or)
            CreateNewOrder() : Order
            GetOrderByID(Integer id) : Order
    }
    class ClientManager {
    All methods from ClientProxy
    }
    class OrderManager {
    All methods from OrderProxy
    }
    class LegacyClientAdapter {
        GetLegClientList() : List<Client>
        GetLegClientByPNumber(String pNumber) : Client
    }
    class LegacyOrderAdapter {
        GetLegOrderList() : List<Order>
        GetLegOrderByCode(String code) : Order
    }
}

package RestControllers #DDDDDD {
    class ClientRestController {
        CreateNewClient() : Client
        GetClientList() : List<Client>
    }
    class OrderRestController {
        CreateNewOrder() : Order
        GetOrderList() : List<Order>
    }
    class ServiceRequestRestController {
        GetSRListByUser(User u) : List<ServiceRequest>
        SetSRStatus(ServiceRequest sr, Status st)
    }
    class IncidentRestController {
        GetIncListByUser(User u) : List<Incident>
        SetIncStatus(Incident inc, Status st)
    }
}

ServiceRequestManager o-- ServiceRequestRepository
IncidentManager o-- IncidentRepository
ClientManager o-- ClientRepository
OrderManager o-- OrderRepository
IncidentRestController o-- IncidentManager
ServiceRequestRestController o-- ServiceRequestManager
ClientRestController o-- ClientProxy
OrderRestController o-- OrderProxy
ClientProxy o-- ClientManager
ClientProxy o-- LegacyClientAdapter
OrderProxy o-- OrderManager
OrderProxy o- LegacyOrderAdapter
ServiceRequestRepository ..> Servicerequest
IncidentRepository ..> Incident
ClientRepository ..> Client
OrderRepository ..> Order

@enduml