@startuml
'https://plantuml.com/deployment-diagram
left to right direction
skinparam linetype ortho
node "Application Server" as Apps {
    node Services {
        component Clients
        component Orders
        component ServiceRequests
        component Incidents
    }
}


node "Replication cluster" as Database {
    database Postgers {
        artifact "Clients schema"
        artifact "Orders schema"
        artifact "ServiceRequests schema"
        artifact "Incidents schema"
    }
}

node Keycloak {
    artifact Realm
}

node Grafana {
    artifact Dashboard
}

node Prometheus {
    database Clickhouse
}

Apps --> Database
Services --> Keycloak
Prometheus --> Services
Dashboard --> Prometheus
Dashboard --> Database
@enduml