@startuml
!include hdr.puml

title HELPDesk DB ER diagram

entity "SERVICEREQUEST" as request {
  *servicerequest_id : number <<generated>>
  --
  requesttime : datetime
  clientid : number
  narrative : text
  userid : number
}
note right: **clientid** and **userid** are not FK \nbecause these entities are not\npart of our DB

entity "INCIDENT" as incident {
  *incident_id : number <<generated>>
  --
  incidenttime : datetime
  serviceid : number
  orderid : number
  *servicerequest_id : number <<FK>>
}
note left: **orderid** and **serviceid** are not FK \nbecause these entities are not\npart of our DB

entity "STATUS" as status {
  *status_id : number <<generated>>
  --
  statustime : datetime
  status : enum
  narrative : text
  *incident_id : number <<FK>>
  *servicerequest_id : number <<FK>>
}


request ||..o| incident
request ||..|{ status
incident ||..|{ status

legend right
"||..|| - One-to-One"
"||..|{ - One-to-Many"
"||..o{ - Zero-to-Many"
"||..o| - Zero-to-One"
endlegend

@enduml