@startuml
!include hdr.puml

title ServiceManager DB ER diagram

entity "SERVICEREQUEST" as servicerequest {
  *servicerequest_id : number <<generated>>
  --
  requesttime : datetime
  narrative : text
  legacyclientid : number
  userid : number
}
'note right: **clientid** and **userid** are not FK \nbecause these entities are not\npart of our DB

entity "INCIDENT" as incident {
  *incident_id : number <<generated>>
  --
  incidenttime : datetime
  businessprocess : text
  userid : number
  *servicerequest_id : number <<FK>>
}
'note left: **orderid** and **serviceid** are not FK \nbecause these entities are not\npart of our DB

entity "STATUS" as status {
  *status_id : number <<generated>>
  --
  statustime : datetime
  status : enum
  narrative : text
  *incident_id : number <<FK>>
  *servicerequest_id : number <<FK>>
}

entity "CLIENT" as client {
  *client_id : number <<generated>>
  --
  name : text
  middlename : text
  surname : text
  phonenumber : text <<Unique>>
  email : text
  inn : number
  firmname : text
  *servicerequest_id : number <<FK>>
}

entity "SERVICE" as service {
  *service_id : number <<generated>>
  --
  code : text <<Unique>>
  description : text
  email : text
  *incident_id : number <<FK>>
}

entity "SERVICEGROUP" as servicegroup {
  *servicegroup_id : number <<generated>>
  --
  code : text <<Unique>>
  description : text
  managerid : number
  *service_id : number <<FK>>
}

servicerequest ||..o| incident
servicerequest ||..|{ status
incident ||..|{ status
servicerequest ||..o| client
service ||..|| servicegroup
incident ||..|| service

legend right
"||..|| - One-to-One"
"||..|{ - One-to-Many"
"||..o{ - Zero-to-Many"
"||..o| - Zero-to-One"
endlegend

@enduml