@startuml
autonumber
title Вход/выход из системы с использованием Keycloak SSO [Single sign-on]

box "Frontend" #LightCyan
	participant "Пользователь (Браузер)" as Browser
	participant "Веб приложение" as WebApplication
end box
box "Backend" #LightBlue
	participant Keycloak
end box
== Вход в систему ==
alt Не проверенный
    Browser -> WebApplication : запросить SPA
    activate WebApplication
    WebApplication -> WebApplication : проверить SSO
    WebApplication -> Browser : перенаправление на страницу входа в систему keycloak
    deactivate WebApplication

    Browser -> Keycloak : запросить страницу входа в систему
    Keycloak -> Browser  : страница входа в систему
    activate Keycloak
    Browser -> Keycloak : login
    Keycloak -> Browser: перенаправление SPA и кода аутентификации
    deactivate Keycloak
    Browser -> WebApplication : запрос SPA
    activate WebApplication
    WebApplication -> WebApplication : проверить SSO
    WebApplication -> Keycloak : запросить маркер доступа
    deactivate WebApplication
    Keycloak -> WebApplication: маркер доступа + маркер обновления
end
alt Подтвержденный
    activate WebApplication
    WebApplication -> WebApplication : хранить токен предъявителя
    WebApplication -> WebApplication : внедрить токен предъявителя в HEADER HTTP-запроса
    == Выход из системы ==
    WebApplication -> WebApplication : выход из системы
    WebApplication -> Keycloak: выход из системы
    deactivate WebApplication
end
alt Не проверенный
    Keycloak -> Browser : перенаправить
    Browser -> WebApplication : запрос SPA
end
@enduml

