@startuml
!include hdr.puml


[*] --> OPENED
OPENED -> ASSIGNED
ASSIGNED -> OPENED
ASSIGNED -> CLOSED
OPENED -> CLOSED : обращение заведено по ошибке
CLOSED --> [*]
OPENED : Обращение создано по звонку клиента,\nк обращению привязаны клиент и заказ
ASSIGNED : По обращению выбрана услуга\nи связанная с ней рабочая группа SL3\nа также создан заказ и инцидент
CLOSED : обращение закрыто
@enduml