@startuml
!include hdr.puml


[*] --> OPENED
OPENED -> ASSIGNED
ASSIGNED -> INWORK
ASSIGNED -> OPENED
INWORK -> IMPLEMENTED
INWORK --> NEEDSREFINEMENT
NEEDSREFINEMENT --> INWORK
IMPLEMENTED -> CLOSED
OPENED -> CLOSED : инцидент заведен по ошибке
CLOSED --> [*]
OPENED : Инцидент создан после\nсоздания обращения
ASSIGNED : Инцидент назначен на\nсотрудника SL3
INWORK : Сотрудник SL3 на которого назначили\nинцидент взял его в работу
NEEDSREFINEMENT : требуются уточнения
IMPLEMENTED : инцидент выполнен
CLOSED : инцидент закрыт c закрытием\nсоответствующего обращения
@enduml