@startuml
!include hdr.puml

title SERVICEREQUEST entity state machine

[*] --> OPENED
OPENED -> ASSIGNED
ASSIGNED -> OPENED
ASSIGNED -> CLOSED
OPENED -> CLOSED : обращение заведено по ошибке
CLOSED --> [*]
OPENED : Обращение создано по звонку клиента
ASSIGNED : По обращению выбрана услуга\nи оно назначено на группу SL3\nа также создан заказ и инцидент
CLOSED : обращение закрыто
@enduml